// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzHMD9tAc7POpsMe1zd38EJ5BJbxgU3FA',
    appId: '1:344890845400:web:1b32d160c02385a3020fad',
    messagingSenderId: '344890845400',
    projectId: 'smart-hydroponic-app-26baa',
    authDomain: 'smart-hydroponic-app-26baa.firebaseapp.com',
    storageBucket: 'smart-hydroponic-app-26baa.firebasestorage.app',
    measurementId: 'G-RPD0N0CMPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrbZHtvs9QV0PYg_6aRixRPIicstMOfvA',
    appId: '1:344890845400:android:6c9239123303284a020fad',
    messagingSenderId: '344890845400',
    projectId: 'smart-hydroponic-app-26baa',
    storageBucket: 'smart-hydroponic-app-26baa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_UAtyLDanb3vEgGm2zitPuowOA0P0cRY',
    appId: '1:344890845400:ios:669be09bb12b5081020fad',
    messagingSenderId: '344890845400',
    projectId: 'smart-hydroponic-app-26baa',
    storageBucket: 'smart-hydroponic-app-26baa.firebasestorage.app',
    iosBundleId: 'com.example.smartHydroponicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_UAtyLDanb3vEgGm2zitPuowOA0P0cRY',
    appId: '1:344890845400:ios:669be09bb12b5081020fad',
    messagingSenderId: '344890845400',
    projectId: 'smart-hydroponic-app-26baa',
    storageBucket: 'smart-hydroponic-app-26baa.firebasestorage.app',
    iosBundleId: 'com.example.smartHydroponicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzHMD9tAc7POpsMe1zd38EJ5BJbxgU3FA',
    appId: '1:344890845400:web:fa5f3de519f6f991020fad',
    messagingSenderId: '344890845400',
    projectId: 'smart-hydroponic-app-26baa',
    authDomain: 'smart-hydroponic-app-26baa.firebaseapp.com',
    storageBucket: 'smart-hydroponic-app-26baa.firebasestorage.app',
    measurementId: 'G-DGL4V8HM7Q',
  );
}
